name: fetch-images

on:
  schedule:
    - cron: "0 */6 * * *"   # 6시간마다(UTC)
  workflow_dispatch: {}      # 수동 실행 허용

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare folders
        shell: bash
        run: |
          mkdir -p images
          test -f images/catalog.json || echo '{"files":[]}' > images/catalog.json

      - name: Download 4 images (no conditional check)
        shell: bash
        run: |
          URLS=(
            "https://backend.wplace.live/files/s0/tiles/1741/791.png"
            "https://backend.wplace.live/files/s0/tiles/1742/791.png"
            "https://backend.wplace.live/files/s0/tiles/1741/790.png"
            "https://backend.wplace.live/files/s0/tiles/1742/790.png"
          )

          DAY="$(date -u +'%Y%m%d')"
          TIM="$(date -u +'%H%M%S')"
          tmpdir="$(mktemp -d)"

          for u in "${URLS[@]}"; do
            # URL 패턴: .../tiles/{A}/{B}.png  -> A와 B 추출
            if [[ "$u" =~ /tiles/([0-9]+)/([0-9]+)\.png$ ]]; then
              A="${BASH_REMATCH[13]}"
              B="${BASH_REMATCH[1]}"
            else
              A="img"; B="$(date -u +'%H%M%S')"
            fi

            name="${A}x${B}_${DAY}_${TIM}.png"
            out="${tmpdir}/${name}"

            # 항상 원본 다운로드(조건부 헤더 없음)
            curl -L --fail --silent --show-error -o "$out" "$u" || true

            if [ -s "$out" ]; then
              mv "$out" "images/${name}"
              echo "Saved ${name}"
            else
              echo "Download failed or empty for $u"
            fi
          done

      - name: Update catalog.json
        shell: bash
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = require('path');
          const crypto = require('crypto');
          const dir = 'images';
          const catalogPath = path.join(dir, 'catalog.json');

          let catalog = { files: [] };
          if (fs.existsSync(catalogPath)) {
            try { catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8') || '{"files":[]}'); }
            catch { catalog = { files: [] }; }
          }

          const files = fs.readdirSync(dir).filter(f => /\.(png|jpg|jpeg|gif|webp)$/i.test(f));
          const known = new Set(catalog.files.map(x => x.name));

          for (const f of files) {
            if (!known.has(f)) {
              const p = path.join(dir, f);
              const sha = crypto.createHash('md5').update(fs.readFileSync(p)).digest('hex').slice(0,12);
              catalog.files.push({ name: f, sha, ts: new Date().toISOString() });
            }
          }

          catalog.files = catalog.files.sort((a,b)=>a.name.localeCompare(b.name)).slice(-2000);
          fs.writeFileSync(catalogPath, JSON.stringify(catalog, null, 2));
          console.log('files in catalog:', catalog.files.length);
          NODE

      - name: Commit and push if changed
        shell: bash
        run: |
          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: fetch images (no-conditional) [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
