name: fetch-images

on:
  schedule:
    - cron: "30 */6 * * *"   # 6시간마다(UTC)
  workflow_dispatch: {}      # 수동 실행 허용

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare folders
        shell: bash
        run: |
          mkdir -p images
          test -f images/catalog.json || echo '{"files":[]}' > images/catalog.json

      - name: Download images (robust naming)
        shell: bash
        run: |
          URLS=(
            "https://backend.wplace.live/files/s0/tiles/1741/789.png"
            "https://backend.wplace.live/files/s0/tiles/1742/789.png"
            "https://backend.wplace.live/files/s0/tiles/1743/789.png"
            "https://backend.wplace.live/files/s0/tiles/1741/790.png"
            "https://backend.wplace.live/files/s0/tiles/1742/790.png"
            "https://backend.wplace.live/files/s0/tiles/1743/790.png"
            "https://backend.wplace.live/files/s0/tiles/1741/791.png"
            "https://backend.wplace.live/files/s0/tiles/1742/791.png"
            "https://backend.wplace.live/files/s0/tiles/1743/791.png"
          )
          DAY="$(TZ=Asia/Seoul date +'%Y%m%d')"
          TIM="$(TZ=Asia/Seoul date +'%H%M%S')"
          tmpdir="$(mktemp -d)"

          for u in "${URLS[@]}"; do
            # 1) /tiles/ 앞부분 제거
            path="${u#*/tiles/}"        # 예: 1741/791.png [4][1]
            # 2) 첫 슬래시 전까지 = A
            A="${path%%/*}"             # 예: 1741 [4]
            # 3) 첫 슬래시 뒤(파일명)에서 확장자 제거 = B
            tail="${path#*/}"           # 예: 791.png [4]
            B="${tail%.*}"              # 예: 791 [4]

            # 안전: 숫자만 남기기
            A="${A//[^0-9]/}"           # 글자 제거 [4]
            B="${B//[^0-9]/}"

            name="${DAY}_${TIM}_${A}x${B}.png"
            out="${tmpdir}/${name}"

            curl -L --fail --silent --show-error -o "$out" "$u" || true  # 원본 그대로 다운로드 [14]
            if [ -s "$out" ]; then
              mv "$out" "images/${name}"
              echo "Saved ${name}"
            else
              echo "Download failed or empty for $u"
            fi
          done

      - name: Update catalog.json
        shell: bash
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = require('path');
          const crypto = require('crypto');
          const dir = 'images';
          const catalogPath = path.join(dir, 'catalog.json');

          let catalog = { files: [] };
          if (fs.existsSync(catalogPath)) {
            try { catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8') || '{"files":[]}'); }
            catch { catalog = { files: [] }; }
          }

          const files = fs.readdirSync(dir).filter(f => /\.(png|jpg|jpeg|gif|webp)$/i.test(f));
          const known = new Set(catalog.files.map(x => x.name));

          for (const f of files) {
            if (!known.has(f)) {
              const p = path.join(dir, f);
              const sha = crypto.createHash('md5').update(fs.readFileSync(p)).digest('hex').slice(0,12);
              catalog.files.push({ name: f, sha, ts: new Date().toISOString() });
            }
          }

          catalog.files = catalog.files.sort((a,b)=>a.name.localeCompare(b.name)).slice(-2000);
          fs.writeFileSync(catalogPath, JSON.stringify(catalog, null, 2));
          console.log('files in catalog:', catalog.files.length);
          NODE

      - name: Commit and push if changed
        shell: bash
        run: |
          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: fetch images (no-conditional) [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
