name: fetch-images

on:
  schedule:
    - cron: "0 */6 * * *"   # 6시간마다(UTC 기준) 실행
  workflow_dispatch: {}      # 수동 실행도 허용

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          mkdir -p images
          test -f images/catalog.json || echo '{"files":[]}' > images/catalog.json

      - name: Download 4 images with custom names (fixed)
        shell: bash
        run: |
          URLS=(
            "https://backend.wplace.live/files/s0/tiles/1741/791.png"
            "https://backend.wplace.live/files/s0/tiles/1742/791.png"
            "https://backend.wplace.live/files/s0/tiles/1741/790.png"
            "https://backend.wplace.live/files/s0/tiles/1742/790.png"
          )

          ts_now="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          DAY="$(date -u +'%Y%m%d')"
          TIM="$(date -u +'%H%M%S')"
          tmpdir="$(mktemp -d)"

          # 이전 실행에서만 가져온 If-Modified-Since 기준 시각(이번 실행 중에는 고정)
          ims=""
          if [ -f images/latest.txt ]; then
            ims="$(date -u -r images/latest.txt +'%a, %d %b %Y %H:%M:%S GMT' 2>/dev/null || true)"
          fi

          saved=0
          for u in "${URLS[@]}"; do
            # URL에서 /tiles/{A}/{B}.png 추출(정규식으로 안전하게)
            if [[ "$u" =~ /tiles/([0-9]+)/([0-9]+)\.png$ ]]; then
              A="${BASH_REMATCH[1]}"
              B="${BASH_REMATCH[13]}"
            else
              # 예외 시 도메인_타임스탬프로 대체
              A="img"; B="$(date -u +'%H%M%S')"
            fi
            name="${A}x${B}_${DAY}_${TIM}.png"

            curl -L --fail --silent --show-error \
                 ${ims:+-H "If-Modified-Since: $ims"} \
                 -o "${tmpdir}/${name}" "$u" || true

            if [ -s "${tmpdir}/${name}" ]; then
              mv "${tmpdir}/${name}" "images/${name}"
              echo "Saved ${name}"
              saved=$((saved+1))
            else
              echo "No update for $u"
            fi
          done

          # 이번 실행에서 실제 저장이 있었을 때만 latest.txt를 갱신
          if [ "$saved" -gt 0 ]; then
            echo "$ts_now" > images/latest.txt
          fi

      - name: Update catalog.json
        shell: bash
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = require('path');
          const crypto = require('crypto');

          const dir = 'images';
          const catalogPath = path.join(dir, 'catalog.json');

          let catalog = { files: [] };
          if (fs.existsSync(catalogPath)) {
            try { catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8') || '{"files":[]}'); }
            catch { catalog = { files: [] }; }
          }

          const files = fs.readdirSync(dir).filter(f => /\.(png|jpg|jpeg|gif|webp)$/i.test(f));
          const known = new Set(catalog.files.map(x => x.name));

          for (const f of files) {
            if (!known.has(f)) {
              const p = path.join(dir, f);
              const sha = crypto.createHash('md5').update(fs.readFileSync(p)).digest('hex').slice(0,12);
              catalog.files.push({ name: f, sha, ts: new Date().toISOString() });
            }
          }

          // 최근 2000개 메타만 유지(원하는 값으로 조정 가능)
          catalog.files = catalog.files.sort((a,b)=>a.name.localeCompare(b.name)).slice(-2000);
          fs.writeFileSync(catalogPath, JSON.stringify(catalog, null, 2));
          console.log('files in catalog:', catalog.files.length);
          NODE

      - name: Commit and push if changed
        run: |
          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: fetch images [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
